# Generated by Django 5.0.7 on 2024-11-24 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_inventorycategory_paymentmethod_supplier_inventory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='production',
            name='material',
        ),
        migrations.RemoveField(
            model_name='service',
            name='pricing_option_id',
        ),
        migrations.AddField(
            model_name='pricingoption',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='pricingoption',
            name='discount_name',
            field=models.CharField(blank=True, default='', help_text='Name or type of the discount', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pricingoption',
            name='discount_type',
            field=models.CharField(blank=True, choices=[('fixed', 'Fixed Amount'), ('percentage', 'Percentage')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='production',
            name='materials',
            field=models.ManyToManyField(related_name='production_jobs', to='system.inventory'),
        ),
        migrations.AddField(
            model_name='service',
            name='pricing_options',
            field=models.ManyToManyField(blank=True, related_name='services', to='system.pricingoption'),
        ),
    ]
