# Generated by Django 5.0.7 on 2024-11-24 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_remove_production_material_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the business or organization.', max_length=255)),
                ('address', models.TextField(help_text='Complete address of the business.')),
                ('contact_number', models.CharField(blank=True, help_text='Business contact number.', max_length=15, null=True)),
                ('email', models.EmailField(blank=True, help_text='Business email address.', max_length=254, null=True)),
                ('tax_identification_number', models.CharField(blank=True, help_text='Tax ID or equivalent.', max_length=50, null=True)),
                ('logo', models.ImageField(blank=True, help_text='Upload the business logo.', null=True, upload_to='business_logos/')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('equipment_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('condition', models.CharField(choices=[('new', 'New'), ('used', 'Used')], max_length=50)),
            ],
        ),
    ]
