# Generated by Django 5.0.7 on 2024-11-24 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_businessdetails_equipment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='USD', help_text='Default currency for transactions.', max_length=10)),
                ('timezone', models.CharField(default='UTC', help_text='System default timezone.', max_length=50)),
                ('date_format', models.CharField(default='YYYY-MM-DD', help_text='Default format for dates.', max_length=20)),
                ('language', models.CharField(default='en', help_text='Default language for the system.', max_length=20)),
                ('smtp_server', models.CharField(blank=True, help_text='SMTP server address.', max_length=255, null=True)),
                ('smtp_port', models.PositiveIntegerField(blank=True, help_text='SMTP port number.', null=True)),
                ('smtp_email', models.EmailField(blank=True, help_text='SMTP email address.', max_length=254, null=True)),
                ('smtp_password', models.CharField(blank=True, help_text='SMTP email password.', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='Description of the action performed.', max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Time when the action occurred.')),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the action.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
