# Generated by Django 5.0.7 on 2024-11-25 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_systemsettings_auditlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='pricingoption',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='pricingoption',
            name='discount_name',
        ),
        migrations.RemoveField(
            model_name='pricingoption',
            name='discount_type',
        ),
        migrations.AddField(
            model_name='payment',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='discount_name',
            field=models.CharField(blank=True, default='', help_text='Name or type of the discount', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='discount_type',
            field=models.CharField(blank=True, choices=[('fixed', 'Fixed Amount'), ('percentage', 'Percentage')], max_length=10, null=True),
        ),
    ]
