# Generated by Django 5.0.7 on 2024-11-25 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_payment_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomizationOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='service',
            name='customization_options',
            field=models.CharField(blank=True, choices=[], max_length=255),
        ),
    ]
