# Generated by Django 5.0.7 on 2024-11-25 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_customizationoption_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='customization_options',
        ),
        migrations.AddField(
            model_name='service',
            name='customization_options',
            field=models.ManyToManyField(blank=True, related_name='services', to='system.customizationoption'),
        ),
    ]
