# Generated by Django 5.0.7 on 2024-11-26 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_remove_service_customization_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricingoption',
            name='code',
        ),
        migrations.AddField(
            model_name='pricingoption',
            name='customization_option',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pricing_options', to='system.customizationoption'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='service',
            name='pricing_options',
        ),
        migrations.AddField(
            model_name='service',
            name='pricing_options',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='system.pricingoption'),
        ),
    ]
