# Generated by Django 5.0.7 on 2024-11-29 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0010_remove_pricingoption_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='unit_of_measurement',
            field=models.CharField(choices=[('qty', 'Quantity'), ('liters', 'Liters'), ('meters', 'Meters'), ('mm', 'Milimeters'), ('rolls', 'Rolls'), ('sheets', 'Sheets'), ('kg', 'Kilograms'), ('pcs', 'Pieces'), ('cm', 'Centimeters'), ('grams', 'Grams')], default='qty', max_length=20),
        ),
    ]
