# Generated by Django 5.0.7 on 2024-11-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0011_inventory_unit_of_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='unit_of_measurement',
            field=models.CharField(choices=[('qty', 'qty'), ('liters', 'liters'), ('meters', 'meters'), ('mm', 'mm'), ('rolls', 'rolls'), ('sheets', 'sheets'), ('kg', 'kg'), ('pcs', 'pcs'), ('cm', 'cm'), ('grams', 'grams')], default='qty', max_length=20),
        ),
    ]
