# Generated by Django 5.0.7 on 2024-11-30 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0012_alter_inventory_unit_of_measurement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='contact_details',
            new_name='contact_number',
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
