# Generated by Django 5.0.7 on 2024-12-01 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0013_rename_contact_details_customer_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('working', 'Working'), ('damaged', 'Damage'), ('broken', 'Broken')], max_length=50),
        ),
    ]
