# Generated by Django 5.0.7 on 2024-12-01 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0014_alter_equipment_condition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='pricing_options',
        ),
        migrations.AddField(
            model_name='pricingoption',
            name='service',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='pricing_options', to='system.service'),
            preserve_default=False,
        ),
    ]
