# Generated by Django 5.0.7 on 2024-12-04 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0015_remove_service_pricing_options_pricingoption_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customization_options',
            field=models.ManyToManyField(blank=True, related_name='orders', to='system.customizationoption'),
        ),
    ]
