# Generated by Django 5.0.7 on 2024-12-05 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0016_order_customization_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customization_options',
        ),
    ]
