# Generated by Django 5.0.4 on 2024-12-05 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0018_order_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_queue',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
