# Generated by Django 5.0.4 on 2024-12-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0020_order_completed_or_cancelled_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='completed_or_cancelled',
            field=models.DateTimeField(null=True),
        ),
    ]
