# Generated by Django 5.0.4 on 2024-12-09 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0021_alter_order_completed_or_cancelled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('ON_HOLD', 'On Hold'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='NOT_STARTED', max_length=20),
        ),
    ]
