# Generated by Django 5.0.4 on 2024-12-09 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0022_alter_production_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorycategory',
            name='associated_equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='system.equipment'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('working', 'Working'), ('damaged', 'Damaged'), ('broken', 'Broken')], max_length=50),
        ),
    ]
