# Generated by Django 5.0.4 on 2024-12-10 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0023_inventorycategory_associated_equipment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='priority',
            field=models.CharField(choices=[('HIGH', 'High'), ('MODERATE', 'Moderate'), ('LOW', 'Low')], default='MODERATE', max_length=10),
        ),
        migrations.AlterField(
            model_name='production',
            name='equipment_assigned',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='production',
            name='materials',
            field=models.ManyToManyField(related_name='productions', to='system.inventory'),
        ),
        migrations.AlterField(
            model_name='production',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productions', to='system.order'),
        ),
        migrations.AlterField(
            model_name='production',
            name='quality_checks',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='production',
            name='status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('ON_HOLD', 'On Hold'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='NOT_STARTED', max_length=50),
        ),
    ]
