# Generated by Django 5.0.4 on 2024-12-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0024_production_priority_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorycategory',
            name='associated_equipment',
        ),
        migrations.AddField(
            model_name='inventorycategory',
            name='associated_equipment',
            field=models.ManyToManyField(blank=True, related_name='categories', to='system.equipment'),
        ),
    ]
