# Generated by Django 5.0.4 on 2024-12-10 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0025_remove_inventorycategory_associated_equipment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('ON_HOLD', 'On Hold'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='NOT_STARTED', max_length=50),
        ),
    ]
